export const TableData = [
  {
    registrationDate: "22.10.12",
    nickName: "Sonny",
    userId: "fcjscho97",
    email: "ABCDEW1234",
    title: " 특수교육학개론 개별화 교육 프로그램과 긍정적 행동 지원1",
    id: 1,
    classification: "학과별  전공자료 > 인문대학> 영미언어문화> 중간고사1",
    reason: "폭언,욕설",
  },
  {
    registrationDate: "22.10.12",
    nickName: "Sonny",
    userId: "fcjscho97",
    email: "ABCDEW1234",
    title: " 특수교육학개론 개별화 교육 프로그램과 긍정적 행동 지원2",
    id: 2,
    classification: "학과별  전공자료 > 인문대학> 영미언어문화> 중간고사2",
    reason: "폭언,욕설",
  },
  {
    registrationDate: "22.10.12",
    nickName: "Sonny",
    userId: "fcjscho97",
    email: "ABCDEW1234",
    title: " 특수교육학개론 개별화 교육 프로그램과 긍정적 행동 지원3",
    classification: "학과별  전공자료 > 인문대학> 영미언어문화> 중간고사",
    reason: "폭언,욕설",
    id: 3,
  },
  {
    registrationDate: "22.10.12",
    nickName: "Sonny",
    userId: "fcjscho97",
    email: "ABCDEW1234",
    title: " 특수교육학개론 개별화 교육 프로그램과 긍정적 행동 지원4",
    classification: "학과별  전공자료 > 인문대학> 영미언어문화> 중간고사",
    reason: "폭언,욕설",
    id: 4,
  },
];
