export const TableData = [
  {
    registrationDate: "22.10.12",
    nickName: "Sonny",
    userId: "fcjscho97",
    email: "ABCDEW1234",
    id: 1,
    reason: "스팸 댓글 혹은 홍보용 댓글1",
    commentData: "아 퇴사 마렵다.아 퇴사 마렵다1",
    reporterId: "Vincemnt1234",
  },
  {
    registrationDate: "22.10.12",
    nickName: "Sonny",
    userId: "fcjscho97",
    email: "ABCDEW1234",
    id: 2,
    reason: "스팸 댓글 혹은 홍보용 댓글2",
    commentData: "아 퇴사 마렵다.아 퇴사 마렵다2.",
    reporterId: "Vincemnt1234",
  },
  {
    registrationDate: "22.10.12",
    nickName: "Sonny",
    userId: "fcjscho97",
    email: "ABCDEW1234",
    reason: "스팸 댓글 혹은 홍보용 댓글",
    commentData: "아 퇴사 마렵다.아 퇴사 마렵다.",
    reporterId: "Vincemnt1234",
    id: 3,
  },
  {
    registrationDate: "22.10.12",
    nickName: "Sonny",
    userId: "fcjscho97",
    email: "ABCDEW1234",
    reason: "스팸 댓글 혹은 홍보용 댓글",
    id: 4,
    commentData: "아 퇴사 마렵다.아 퇴사 마렵다.",
    reporterId: "Vincemnt1234",
  },
];
